/**
 * Two tiers, and the distinction matters.
 *
 *   `built`  — products Airaf owns end to end. Stacks below were verified
 *              against the GitHub API (languages + package.json), not guessed.
 *   `client` — work delivered for an employer. Framed by contribution, never
 *              as ownership.
 *
 * Rule: never invent a stack. If it isn't verifiable, leave it out.
 */

export type Project = {
  slug: string
  title: string
  kind: "built" | "client"
  /** One line. What it is, not how it makes you feel. */
  blurb: string
  /** Only on `built` — what was actually hard about it. */
  detail?: string
  stack: string[]
  live?: string
  repo?: string
  /** Screenshot in public/images/projects/. Generated by scripts/capture-shots.mjs. */
  image?: string
  /** For client work: the honest scope of involvement. */
  contribution?: string
  /** For client work: the sector, so the index groups into something scannable. */
  sector?: string
  year?: string
}

/* ── Tier 1 · Built & owned ─────────────────────────────────────────── */

export const built: Project[] = [
  {
    slug: "dinely",
    title: "Dinely",
    kind: "built",
    blurb:
      "Reservation and floor-management platform for high-end restaurants.",
    detail:
      "Booking wizard, interactive floor map, and a live staff dashboard over one dataset. The availability rules live in Postgres — ~38k lines of PL/pgSQL — so a double-booking is impossible at the database level, not just the UI.",
    stack: [
      "React",
      "Vite",
      "TypeScript",
      "Supabase",
      "PL/pgSQL",
      "Express",
      "Docker",
      "Fly.io",
    ],
    live: "https://www.dinely.co.uk",
    image: "/images/projects/dinely.png",
    repo: "https://github.com/pizn-01/dinely",
  },
  {
    slug: "ielts-grader",
    title: "IELTS Grader",
    kind: "built",
    blurb: "AI-assisted assessment engine for IELTS writing tasks.",
    detail:
      "Three surfaces — marketing site, candidate app, examiner dashboard — over one Python grading service. Scoring runs against the public band descriptors, so feedback cites its criterion instead of returning an opaque number.",
    stack: ["React", "Node.js", "Python", "Supabase", "Postgres", "Docker"],
    live: "https://ieltsgrader.com",
    image: "/images/projects/ielts-grader.png",
    repo: "https://github.com/pizn-01/IELTS_GRADER",
  },
  {
    slug: "carmazium",
    title: "Carmazium",
    kind: "built",
    blurb: "Cinematic-first automotive marketplace.",
    detail:
      "Gives a listing the weight it has in a physical showroom: full-bleed imagery, scroll-driven sequencing, and a browsing model built around one vehicle at a time rather than a results grid.",
    stack: ["Next.js 15", "Tailwind v4", "Framer Motion", "TypeScript", "Docker"],
    live: "https://carmazium.com",
    image: "/images/projects/carmazium.png",
    repo: "https://github.com/pizn-01/carmazium",
  },
  {
    slug: "whisperoo",
    title: "Whisperoo",
    kind: "built",
    blurb:
      "Maternal and infant care platform connecting parents with clinical experts.",
    detail:
      "Three audiences on one product — parents booking support, experts running a practice, and clinics onboarding staff — each with its own surface over shared scheduling and profile data.",
    // Airaf's standard product stack (confirmed by him — it isn't detectable
    // from the client). Stripe, OpenAI and Cloudflare R2 are part of that
    // stack generally but aren't listed here until confirmed for this build.
    stack: [
      "React",
      "TypeScript",
      "Vite",
      "TanStack Query",
      "Supabase",
      "PostgreSQL",
      "Tailwind CSS",
      "Radix UI",
      "Zod",
    ],
    live: "https://whisperoo.app",
    image: "/images/projects/whisperoo.png",
  },
  {
    slug: "overlap",
    title: "Overlap",
    kind: "built",
    blurb:
      "Studio site for an engineering practice that works US hours from Pakistan.",
    detail:
      "The pitch is a scheduling argument, so the page shows it: paired live clocks and a 24-hour band shading the six hours both sides are online. Hand-written HTML, CSS and JS — no framework to draw a timeline.",
    stack: ["HTML", "CSS", "JavaScript", "Vercel"],
    live: "https://overlap-gules.vercel.app",
    image: "/images/projects/overlap.png",
    repo: "https://github.com/airaf-a633/overlap",
  },
  {
    slug: "finacc",
    title: "FinAcc Solutions",
    kind: "built",
    blurb: "Financial and accounting services platform.",
    detail:
      "Server-rendered throughout, with Supabase SSR and middleware-enforced auth — gated content is never shipped to the client and then hidden.",
    stack: ["Next.js 14", "Supabase SSR", "Framer Motion", "Lenis", "TypeScript"],
    live: "https://finaccsolutions.com",
    image: "/images/projects/finacc.png",
    repo: "https://github.com/pizn-01/finaccsolutions",
  },
]

/* ── Tier 2 · Client & agency work ──────────────────────────────────── */
//
// Delivered under Tech Cabin, LogoPidea, Friends Technologies, and
// Bits and digits. `contribution` states the actual scope — these are not
// owned products and must never be presented as such.
//
// ⚠ Fabletics UK, Edmunds, and Monsoon UK were listed on the previous
// version of this site with invented stacks. They are held out pending
// confirmation of the real scope of involvement. Do not re-add them without it.

export const clientWork: Project[] = [
  {
    slug: "gotrack",
    sector: "Fleet",
    title: "GoTrack UAE",
    kind: "client",
    blurb: "Fleet tracking and GPS monitoring service.",
    contribution: "Front-end build and CMS integration",
    stack: ["WordPress", "JavaScript", "MySQL"],
    live: "https://gotrack.ae/",
  },
  {
    slug: "doctor-on-calls",
    sector: "Healthcare",
    title: "Doctor On Calls",
    kind: "client",
    blurb: "Telemedicine booking for online consultations.",
    contribution: "Front-end build",
    stack: ["React", "WordPress", "PHP"],
    live: "https://doctoroncalls.ae/",
  },
  {
    slug: "uhc-dubai",
    sector: "Healthcare",
    title: "UHC Dubai",
    kind: "client",
    blurb: "Healthcare group site with appointment scheduling.",
    contribution: "Front-end build",
    stack: ["React", "WordPress", "PHP"],
    live: "https://www.uhcdubai.com/",
  },
  {
    slug: "alpha-cargo",
    sector: "Logistics",
    title: "Alpha Cargo",
    kind: "client",
    blurb: "Logistics and shipment tracking.",
    contribution: "Front-end build and CMS integration",
    stack: ["React", "WordPress", "PHP"],
    live: "https://alphacargo.ae/",
  },
  {
    slug: "swiss-arabian",
    sector: "Commerce",
    title: "Swiss Arabian UAE",
    kind: "client",
    blurb: "Fragrance house e-commerce storefront.",
    contribution: "Storefront development",
    stack: ["WooCommerce", "PHP", "JavaScript"],
    live: "https://uae.swissarabian.com/",
  },
  {
    slug: "madame",
    sector: "Commerce",
    title: "Madame Pakistan",
    kind: "client",
    blurb: "Fashion retail e-commerce.",
    contribution: "Storefront development",
    stack: ["Shopify", "JavaScript", "Liquid"],
    live: "https://madame.pk/",
  },
  {
    slug: "speakeasy",
    sector: "Hospitality",
    title: "Speakeasy UAE",
    kind: "client",
    blurb: "Bar and restaurant site with reservations.",
    contribution: "Front-end build",
    stack: ["WordPress", "PHP", "JavaScript"],
    live: "https://speakeasy.ae/",
  },
  {
    slug: "nadia-khan",
    sector: "Media",
    title: "Nadia Khan Official",
    kind: "client",
    blurb: "Media personality site with content management.",
    contribution: "Full site build",
    stack: ["Next.js", "React", "CMS"],
    live: "https://nadiakhanofficial.com/",
  },
  {
    slug: "davis-interior",
    sector: "Design",
    title: "Davis Interior",
    kind: "client",
    blurb: "Interior design studio portfolio.",
    contribution: "Front-end build",
    stack: ["Next.js", "Tailwind CSS"],
    live: "https://davisinterior.com/",
  },
  {
    slug: "original-creator",
    sector: "Agency",
    title: "The Original Creator",
    kind: "client",
    blurb: "Creative agency portfolio platform.",
    contribution: "Front-end build",
    stack: ["Next.js", "TypeScript"],
    live: "https://www.theoriginalcreator.com/",
  },
  {
    slug: "flying-tech",
    sector: "Technology",
    title: "Flying Tech",
    kind: "client",
    blurb: "Technology services company site.",
    contribution: "Front-end build",
    stack: ["Next.js", "React", "Node.js"],
    live: "https://www.flyingtech.co.uk/",
  },
  {
    slug: "litco",
    sector: "Industrial",
    title: "LIT Co Industries",
    kind: "client",
    blurb: "Industrial manufacturer with a product catalogue.",
    contribution: "Front-end build and CMS integration",
    stack: ["Next.js", "TypeScript", "CMS"],
    live: "https://www.litcoindustries.ae/",
  },
  {
    slug: "friends-industries",
    sector: "Industrial",
    title: "Friends Industries",
    kind: "client",
    blurb: "Manufacturing and trading company platform.",
    contribution: "Full site build",
    stack: ["React", "Node.js", "MySQL"],
    live: "https://www.friendsindustries.com.pk/",
  },
  {
    slug: "sgs-cleaning",
    sector: "Services",
    title: "SGS Cleaning",
    kind: "client",
    blurb: "Facilities services site with online booking.",
    contribution: "Front-end build",
    stack: ["WordPress", "PHP", "JavaScript"],
    live: "https://sgscleaning.ae/",
  },
  {
    slug: "me-naturals",
    sector: "Commerce",
    title: "Me Naturals",
    kind: "client",
    blurb: "Skincare e-commerce storefront.",
    contribution: "Storefront development",
    stack: ["WooCommerce", "WordPress", "PHP"],
    live: "https://www.menaturals.net/",
  },
  {
    slug: "crude-oil-capitol",
    sector: "Finance",
    title: "Crude Oil Capitol",
    kind: "client",
    blurb: "Commodity trading information platform.",
    contribution: "Front-end build",
    stack: ["React", "Node.js"],
    live: "https://www.crudeoilcapitol.com/",
  },
]

export const allProjects = [...built, ...clientWork]
